### PR TITLE
WIP: Add TypeScript implementation

### PR DESCRIPTION
**Pull request by 0x77dev**
__*Work in progress*__

Created a PR to get some suggestions about the code
currently on testing stage

### CODE REVIEW

**Comment by bassepeder** [comment]
Looks good to me, but we need to wait for Charles to take a look at it. Have you tested the implementation to see if it works?

**Comment by nopbxlr** [comment]
@bastiantangedal I am not familiar with TypeScript - I'll leave opinions to others.

**Comment by bassepeder** [comment]
@nopbxlr Looks like we're in the same boat then. I guess the only thing to do is to test the implementation, though I do not know how. Maybe an Electron-app would be sufficient?

**Comment by majsi** [comment]
I can do a formal review

**Comment by 0x77dev** [comment]
@majsi that would be great!

There are some troubles with the `encrypt` method will fix this week.

**Comment by 0x77dev** [comment]
@bastiantangedal 
I currently implementing the daemon with HTTP/WS API on Node.js

**Comment by majsi** [comment]
> @majsi that would be great!
> 
> There are some troubles with the `encrypt` method will fix this week.

please let me know when you fix it. Thanks :)

**Comment by 0x77dev** [comment]
Hey guys, it's been a long ~~week~~ _year_.

I no longer have access to a scooter;
can someone provide samples of communications to verify it is working?

Just encrypt/decrypt the sequence to test it.

**Comment by 0x77dev** [comment]
> Hey guys, it's been a long ~~week~~ _year_.
> 
> 
> 
> I no longer have access to a scooter;
> 
> can someone provide samples of communications to verify it is working?
> 
> 
> 
> Just encrypt/decrypt the sequence to test it.

Is there any update?

Can someone please share communication log to test cryptography?

**Comment by bassepeder** [comment]
I thought you got what you needed using `miauth`?

**Pull request closed without merging**
