### PR TITLE
Add better swift implementation

### PR DESCRIPTION
**Pull request by LexNastin**
All the implementations currently stem from the C# implementation by @majsi, and are difficult to read and maintain (although in his defense, that code was mostly automatically generated by a decompiler and was never intended for public use). The Swift implementation also has many faults due to being simple copy paste of the C# version, expecting behaviours that aren't present in the Swift language. There were also multiple mistakes the original author, making his implementation unreliable.

This new Swift implementation completely reimplements all the crypto code and replaces it with more secure functions from CryptoSwift and CryptoKit. It's easier to follow what it's doing and easier to modify as needed as it heavily simplifies on @majsi's original code.

Thanks :)

### CODE REVIEW

**Comment by bassepeder** [comment]
If this is tested and works as expected, I don't see any problem merging this in.

**Comment by LexNastin** [comment]
Yep, is tested and works as expected. Able to auth, encrypt, and decrypt successfully with no data loss or anything.

**Comment by bassepeder** [comment]
Have you also compared behavioral differences between the current version and this one, just to rule out anything weird going on?

**Comment by LexNastin** [comment]
The only ACTUAL behavioral difference is that the current one changes counter from 0 to 2 after the first message, but it appears that that isn't intentional and going from 0 to 1 is perfectly fine, so I made it like that in the new one. Aside from that it's functionally identical and matches the output of the current one :)

Also, this PR doesn't actually remove the current one, it just adds a new file `BetterNinebotCrypto.swift`.

**Comment by LexNastin** [comment]
Also, @nopbxlr said he'll validate my changes later today, so if you want you can leave it to him.

**Comment by bassepeder** [comment]
Alright, sounds good to me. Thank you for the contribution.

**Comment by nopbxlr** [comment]
> The only ACTUAL behavioral difference is that the current one changes counter from 0 to 2 after the first message, but it appears that that isn't intentional and going from 0 to 1 is perfectly fine, so I made it like that in the new one. Aside from that it's functionally identical and matches the output of the current one :)

Wouldn't you believe it.. that's the same bug I found today! It only seems to cause issues on the G65/G2/F2 scooters and that's why I was looking into it. It makes communication very slow as you must always send messages twice for the counter to be ok and to get a reply. Funny timing!

**Review by nopbxlr — APPROVED** [review]

**Comment by robbiet480** [comment]
Thanks for this @LexNastin. I am a decent Swift developer but didn't understand C# and majsi wasn't available to walk me through the code during my translation.

Out of curiosity, what app are you building? Would love to beta test!

**Comment by ArchGryphon9362** [comment]
> Thanks for this @LexNastin. I am a decent Swift developer but didn't understand C# and majsi wasn't available to walk me through the code during my translation.
> 
> Out of curiosity, what app are you building? Would love to beta test!

Check out https://github.com/ArchGryphon9362/asu-app. Thanks for the curiosity. Your implementation was very useful anyways. Thanks for implementing it! The app is currently in rather early stages, but it’s getting there. I’m currently working on fixing Xiaomi specific authentication. It will be a dashboard app with SHFW setting and flashing capabilities. (i’ll be publishing a stripped, dash only app on the App Store later on too, and leaving the one with flashing and SHFW capabilities for sideloading only)

**Comment by robbiet480** [comment]
Hell yeah. Why limit flashing/SHFW to side loading only?

**Comment by lekrsu** [comment]
> Hell yeah. Why limit flashing/SHFW to side loading only?

Apple would by every ounce of their being not allow that on their store.

**Comment by robbiet480** [comment]
Eh, speaking as someone that has constantly pushed the envelope of what's allowed in the store (I authored Home Assistant for iOS) I think you have a good shot of getting it in. Worth a submission to try at least.

**Comment by lekrsu** [comment]
> I think you have a good shot of getting it in. Worth a submission to try at least.

Yeah sure I agree, would be awesome if they would. That would clear up the process for iPhone users quite a bit.

**Comment by ArchGryphon9362** [comment]
> Hell yeah. Why limit flashing/SHFW to side loading only?

It is against App Store policy to publish apps made for the purpose of modifying third party devices, and they often reject apps for simply using third party APIs without the third party’s consent.

> Eh, speaking as someone that has constantly pushed the envelope of what's allowed in the store (I authored Home Assistant for iOS) I think you have a good shot of getting it in. Worth a submission to try at least.

I suppose I COULD try publish the unstripped version and see if Apple tries to shoot me down, but how risky would that be do you think?

P.S. Nice work on HASS iOS, great to have it :)

**Comment by robbiet480** [comment]
If they say no it's not like you're going to lose your developer account. Just submit again stating in the release notes that you removed firmware functionality and you should be fine. Reach out to me elsewhere if thats not the case, Home Assistant has brought me some friends high up at Apple that can help with this kind of thing.

**Comment by ArchGryphon9362** [comment]
> If they say no it's not like you're going to lose your developer account. Just submit again stating in the release notes that you removed firmware functionality and you should be fine. Reach out to me elsewhere if thats not the case, Home Assistant has brought me some friends high up at Apple that can help with this kind of thing.

Thanks! I’ll try it out when the app is ready for that and will be sure to keep you in mind. Hope it goes well!

**Comment by lekrsu** [comment]
> If they say no it's not like you're going to lose your developer account. Just submit again stating in the release notes that you removed firmware functionality and you should be fine. Reach out to me elsewhere if thats not the case, Home Assistant has brought me some friends high up at Apple that can help with this kind of thing.

Was there anything in particular that wouldn't initially allow Home Assistant on the store? Did anything have to be changed source-wise or was it up to convincing?

**Comment by LexNastin** [comment]
Should we move this to Discord or somewhere? It’s getting a bit off topic for this pull request. @robbiet480 could you add me on Discord as @archgryphon9362 and we can make a small group chat.

**Comment by robbiet480** [comment]
@lekrsu @LexNastin was just strolling down memory lane as I'm considering buying a new scooter (G2) which of course must have a great app and saw this comment that I never replied to, so here goes...

We never had an issue actually submitting the app other than metadata things everyone hits (screenshots weren't the right size, change the name to remove "for iOS", that kind of stuff). Where we have tangled with Apple in the past was on special entitlements. For a long time, they didn't want to grant us critical notifications since we weren't one of their expected use cases, and much later, local notifications, again because we weren't one of their expected use cases (cruise ships). It took multiple attempts and in some cases some leverage from higher ups at Apple to get them approved. We're very lucky in that (I've been told) there is a big Home Assistant users contingent inside Apple that is very active on their Slack and some of whom have made themselves known to us, so if we have problems, they can usually be addressed.

I also seem to remember at one point that we considered adding HealthKit support for sensors to HA iOS but were told from sources inside that it would be rejected, as Apple only approves apps for HealthKit that have a strong focus on Health.

Anyway, always available on the HA Discord if you have more questions or need help. @ArchGryphon9362 where's that app 😜

**Comment by LexNastin** [comment]
Hey @robbiet480. Thanks for the info! Very handy. Unfortunately development has slowed to an absolute crawl (more specifically, last commit was about a year ago) due to not having the time in my personal life. I wish I could finish my app, but unfortunately that might not be something I can do anytime soon (or possibly ever). Good news is though, there is a web based app for this that uses WebBluetooth (and there’s a browser on iOS that supports it), so if you need to mess with the config and stuff from iOS, you can use that. Sorry about that! Have a good day :3

**Pull request merged**
